/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TicTacToe;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author tharaka
 */
public class CreateUser extends javax.swing.JFrame {

    /**
     * Creates new form CreateUser
     */
    public CreateUser() {
          setUndecorated(true);
          Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        initComponents();
    //     setExtendedState(Frame.MAXIMIZED_BOTH);
       setLocation((dim.width - jLabel2.getWidth())/2, (dim.height - jLabel2.getHeight())/2);
        setSize(jLabel2.getWidth()-40, jLabel2.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLog = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtName2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/userSelectWindow.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/createUserButton.jpg"))); // NOI18N
        btnLog.setText("jButton2");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        getContentPane().add(btnLog);
        btnLog.setBounds(100, 380, 320, 75);

        txtName.setFont(new java.awt.Font("Carter One", 0, 24)); // NOI18N
        txtName.setText("Player 1");
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(150, 250, 230, 50);

        txtName2.setFont(new java.awt.Font("Carter One", 0, 24)); // NOI18N
        txtName2.setText("Player 2");
        getContentPane().add(txtName2);
        txtName2.setBounds(150, 310, 230, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToe/userSelectWindow.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-30, 0, 550, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        DB db = new DB();
        db.connectLocal();
        String name = txtName.getText();
        String name2 = txtName2.getText();
        ArrayList<String> nameList = db.selectLocal("users", "name", null);
        
   //     System.out.println("################################");
        if(nameList.contains(name)){
            
            
        }else{
            // user doesn't exist
            Table table = new Table();
            Recode recode = new Recode(3, name, "name");
            table.addRecode(recode);
            recode = new Recode(0, "0", "marks");
            table.addRecode(recode);
            db.addLocal("users", table);
        }
        
        if(nameList.contains(name2)){
            
            
        }else{
            // user doesn't exist
            Table table = new Table();
            Recode recode = new Recode(3, name2, "name");
            table.addRecode(recode);
            recode = new Recode(0, "0", "marks");
            table.addRecode(recode);
            db.addLocal("users", table);
        }
        
        Support sup = new Support(db, name, name2);
        MainMenue mainw = new MainMenue();
        mainw.setSup(sup);
        mainw.show();
        this.dispose();
        
    }//GEN-LAST:event_btnLogActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    // End of variables declaration//GEN-END:variables
}
